apiVersion: ecr.mobb.redhat.com/v1alpha1
kind: Secret
metadata:
  name: ecr-secret
  namespace: {{ $.Values.projectName }}-{{ $.Values.environment }}
spec:
  ecr_registry:
    {{ printf "%s.dkr.ecr.%s.amazonaws.com" .Values.awsAccountId .Values.awsRegion }}
  frequency: 10h
  generated_secret_name: ecr-docker-secret
  region: {{ .Values.awsRegion }}
