{{- range $app := .Values.applications }}
{{- range .secrets }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-{{ $.Values.projectName }}-{{ .name }}
  namespace: {{ $.Values.projectName }}-{{ $.Values.environment}}
spec:
  type: kv-v2

  # mount path
  mount: secret

  # path of the secret
  path:  {{ .path }}

  # dest k8s secret
  destination:
    name: secretkv-{{ $app.name }}-{{ .name }}
    create: true

  # static secret refresh interval
  refreshAfter: 90s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: static-auth
---
{{- end }}
{{- end }}
